server:
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: ${TASKER_DB_URL}
    username: ${TASKER_DB_USERNAME}
    password: ${TASKER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

tasker:
  telegram:
    enabled: true
  prometheus:
    username: ${TASKER_PROMETHEUS_USERNAME}
    password: ${TASKER_PROMETHEUS_PASSWORD}
