spring:
  profiles:
    active: dev
  application:
    name: taskboard
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  servlet:
    session:
      timeout: 14d
      cookie:
        http-only: true
        same-site: lax
        max-age: 1209600

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

tasker:
  telegram:
    bot-token: ${TASKER_TELEGRAM_BOT_TOKEN:}
    bot-username: ${TASKER_TELEGRAM_BOT_USERNAME:}
  prometheus:
    username: ${TASKER_PROMETHEUS_USERNAME:prometheus}
    password: ${TASKER_PROMETHEUS_PASSWORD:prometheus-dev}
