spring:
  datasource:
    url: jdbc:h2:mem:taskboard;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true


logging:
  level:
    # Enable to view SQL - lots of noise
    # org.springframework.jdbc.core.JdbcTemplate: DEBUG
    dev.itayp: DEBUG