import type { Task, UserSettings, Category } from './types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-work',     label: 'Work',     swatchId: 'sunshine' },
  { id: 'cat-personal', label: 'Personal', swatchId: 'blossom' },
  { id: 'cat-ideas',    label: 'Ideas',    swatchId: 'mint' },
  { id: 'cat-home',     label: 'Home',     swatchId: 'sky' },
  { id: 'cat-errands',  label: 'Errands',  swatchId: 'lilac' },
  { id: 'cat-health',   label: 'Health',   swatchId: 'peach' },
];

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    title: 'Set up CI/CD pipeline for the backend',
    description: 'Configure GitHub Actions to run tests, build the Docker image, and push to the registry. Staging auto-deploys on merge to main.',
    priority: 'high',
    deadline: '2026-04-24',
    estimatedMinutes: 120,
    status: 'todo',
    categoryId: 'cat-work',
    tags: [{ label: 'deep-work', colorId: 'violet' }, { label: 'engineering', colorId: 'sky' }],
    createdAt: '2026-04-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Review Q2 OKRs with the team',
    description: 'Assess progress on each objective, update key results, prepare a summary slide for the all-hands.',
    priority: 'high',
    deadline: '2026-04-24',
    estimatedMinutes: 90,
    status: 'todo',
    categoryId: 'cat-work',
    tags: [{ label: 'in-person', colorId: 'coral' }],
    createdAt: '2026-04-16T09:00:00Z',
  },
  {
    id: '3',
    title: 'Fix leaking faucet',
    description: 'Kitchen tap is dripping — needs a new washer. Picked up parts last weekend.',
    priority: 'medium',
    estimatedMinutes: 45,
    status: 'todo',
    categoryId: 'cat-home',
    tags: [{ label: 'home-improvement', colorId: 'sage' }],
    createdAt: '2026-04-14T18:00:00Z',
  },
  {
    id: '4',
    title: 'Book dentist appointment',
    priority: 'low',
    deadline: '2026-04-30',
    status: 'todo',
    categoryId: 'cat-health',
    tags: [{ label: 'followup', colorId: 'coral' }],
    createdAt: '2026-04-10T12:00:00Z',
  },
  {
    id: '5',
    title: 'Finish "Four Thousand Weeks"',
    description: 'Last three chapters. Bring the book on the train Tuesday.',
    priority: 'low',
    estimatedMinutes: 60,
    status: 'todo',
    categoryId: 'cat-personal',
    tags: [{ label: 'reading', colorId: 'teal' }],
    createdAt: '2026-04-12T20:00:00Z',
  },
  {
    id: '6',
    title: 'Thursday standup slides',
    description: 'Sprint progress, blockers, next steps. Keep it under 10 minutes.',
    priority: 'high',
    deadline: '2026-04-23',
    estimatedMinutes: 60,
    status: 'todo',
    categoryId: 'cat-work',
    tags: [{ label: 'deep-work', colorId: 'violet' }],
    createdAt: '2026-04-17T08:00:00Z',
  },
  {
    id: '7',
    title: 'Grocery run',
    description: 'Out of coffee, fruit, pasta. Check the dairy drawer.',
    priority: 'medium',
    estimatedMinutes: 45,
    status: 'todo',
    categoryId: 'cat-errands',
    tags: [{ label: 'errands', colorId: 'lemon' }],
    createdAt: '2026-04-18T07:00:00Z',
  },
  {
    id: '8',
    title: 'Refactor auth middleware',
    description: 'Remove legacy token path — everyone is on OAuth now. Watch for callers still referencing the old method.',
    url: 'https://github.com/itayp/tasker/issues/42',
    priority: 'medium',
    estimatedMinutes: 90,
    status: 'todo',
    categoryId: 'cat-work',
    tags: [{ label: 'deep-work', colorId: 'violet' }, { label: 'tech-debt', colorId: 'rose' }],
    createdAt: '2026-04-17T14:00:00Z',
  },
  {
    id: '9',
    title: 'Plan sabbatical trip',
    description: 'Route through northern Japan in autumn. Start with rail pass research.',
    priority: 'low',
    status: 'todo',
    categoryId: 'cat-ideas',
    tags: [{ label: 'research', colorId: 'sky' }],
    createdAt: '2026-04-11T21:00:00Z',
  },
  {
    id: '10',
    title: 'Ask landlord about bike storage',
    priority: 'low',
    status: 'todo',
    categoryId: 'cat-home',
    tags: [{ label: 'followup', colorId: 'coral' }],
    createdAt: '2026-04-17T09:00:00Z',
  },
];

export const DEFAULT_SETTINGS: UserSettings = {
  displayName: 'Itay',
  contextBlock:
    'I prefer deep work in the morning, ideally before 11am.\nTuesdays I leave early for school pickup around 3pm.\nI have a hard cap of 5 hours of focused work per day.',
  categories: SEED_CATEGORIES,
};
